version: '2'
services:
    webapp-cassandra:
        container_name: webapp-cassandra
        image: cassandra:2.2.5
        # volumes:
        #     - ~/volumes/jhipster/webapp/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    webapp-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: webapp-cassandra-migration
        links:
            - webapp-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
